/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    enquiries: Enquiry;
    'contact-messages': ContactMessage;
    'estate2-enquiries': Estate2Enquiry;
    'estate2-contact-messages': Estate2ContactMessage;
    'estate2-blogs': Estate2Blog;
    'dholera-estates-blogs': DholeraEstatesBlog;
    'dholera-estates-enquiries': DholeraEstatesEnquiry;
    'dholera-estates-contact-messages': DholeraEstatesContactMessage;
    media: Media;
    blogs: Blog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'estate2-enquiries': Estate2EnquiriesSelect<false> | Estate2EnquiriesSelect<true>;
    'estate2-contact-messages': Estate2ContactMessagesSelect<false> | Estate2ContactMessagesSelect<true>;
    'estate2-blogs': Estate2BlogsSelect<false> | Estate2BlogsSelect<true>;
    'dholera-estates-blogs': DholeraEstatesBlogsSelect<false> | DholeraEstatesBlogsSelect<true>;
    'dholera-estates-enquiries': DholeraEstatesEnquiriesSelect<false> | DholeraEstatesEnquiriesSelect<true>;
    'dholera-estates-contact-messages': DholeraEstatesContactMessagesSelect<false> | DholeraEstatesContactMessagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    'dholera-dashboard': DholeraDashboardWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: string;
  name: string;
  email: string;
  phone: string;
  property?: string | null;
  message?: string | null;
  source?: string | null;
  status?: ('new' | 'contacted' | 'follow-up' | 'qualified' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: string;
  name: string;
  email: string;
  phone: string;
  propertyType: 'residential-plot' | 'sco-plot' | 'industrial-plot' | 'dholera-estates';
  budget: 'below-20-lakhs' | '20-50-lakhs' | '50-lakhs-1-crore' | 'above-1-crore';
  comments?: string | null;
  consent?: boolean | null;
  source?: string | null;
  status?: ('new' | 'contacted' | 'follow-up' | 'qualified' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estate2-enquiries".
 */
export interface Estate2Enquiry {
  id: string;
  name: string;
  email: string;
  phone: string;
  property: string;
  message?: string | null;
  source: 'estate2-popup-form' | 'estate2-side-enquiry-form';
  status?: ('new' | 'contacted' | 'follow-up' | 'qualified' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estate2-contact-messages".
 */
export interface Estate2ContactMessage {
  id: string;
  name: string;
  email: string;
  phone: string;
  propertyType: 'dholera-estate-2';
  budget: 'below-20-lakhs' | '20-50-lakhs' | '50-lakhs-1-crore' | 'above-1-crore';
  comments?: string | null;
  consent: boolean;
  source: string;
  status?: ('new' | 'contacted' | 'follow-up' | 'qualified' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estate2-blogs".
 */
export interface Estate2Blog {
  id: string;
  title: string;
  /**
   * URL slug, for example: investing-in-dholera
   */
  slug: string;
  excerpt: string;
  content: string;
  featuredImage: string | Media;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dholera-estates-blogs".
 */
export interface DholeraEstatesBlog {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  featuredImage: string | Media;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dholera-estates-enquiries".
 */
export interface DholeraEstatesEnquiry {
  id: string;
  name: string;
  email: string;
  phone: string;
  property: string;
  message?: string | null;
  source: 'dholeraestates-popup-form' | 'dholeraestates-side-enquiry-form' | 'dholeraestates-website';
  status?: ('new' | 'contacted' | 'follow-up' | 'qualified' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dholera-estates-contact-messages".
 */
export interface DholeraEstatesContactMessage {
  id: string;
  name: string;
  email: string;
  phone: string;
  propertyType: 'dholera-estates';
  budget: 'below-20-lakhs' | '20-50-lakhs' | '50-lakhs-1-crore' | 'above-1-crore';
  comments?: string | null;
  consent: boolean;
  source: string;
  status?: ('new' | 'contacted' | 'follow-up' | 'qualified' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: string;
  title: string;
  /**
   * URL friendly slug. Example: ridhi-966-1
   */
  slug: string;
  excerpt: string;
  content: string;
  featuredImage: string | Media;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: string | Enquiry;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: string | ContactMessage;
      } | null)
    | ({
        relationTo: 'estate2-enquiries';
        value: string | Estate2Enquiry;
      } | null)
    | ({
        relationTo: 'estate2-contact-messages';
        value: string | Estate2ContactMessage;
      } | null)
    | ({
        relationTo: 'estate2-blogs';
        value: string | Estate2Blog;
      } | null)
    | ({
        relationTo: 'dholera-estates-blogs';
        value: string | DholeraEstatesBlog;
      } | null)
    | ({
        relationTo: 'dholera-estates-enquiries';
        value: string | DholeraEstatesEnquiry;
      } | null)
    | ({
        relationTo: 'dholera-estates-contact-messages';
        value: string | DholeraEstatesContactMessage;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'blogs';
        value: string | Blog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  property?: T;
  message?: T;
  source?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  propertyType?: T;
  budget?: T;
  comments?: T;
  consent?: T;
  source?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estate2-enquiries_select".
 */
export interface Estate2EnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  property?: T;
  message?: T;
  source?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estate2-contact-messages_select".
 */
export interface Estate2ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  propertyType?: T;
  budget?: T;
  comments?: T;
  consent?: T;
  source?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estate2-blogs_select".
 */
export interface Estate2BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dholera-estates-blogs_select".
 */
export interface DholeraEstatesBlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dholera-estates-enquiries_select".
 */
export interface DholeraEstatesEnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  property?: T;
  message?: T;
  source?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dholera-estates-contact-messages_select".
 */
export interface DholeraEstatesContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  propertyType?: T;
  budget?: T;
  comments?: T;
  consent?: T;
  source?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dholera-dashboard_widget".
 */
export interface DholeraDashboardWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}